# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ai_create_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AICharacterCreation(object):
    def setupUi(self, AICharacterCreation):
        AICharacterCreation.setObjectName("AICharacterCreation")
        AICharacterCreation.resize(309, 450)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AICharacterCreation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AICharacterCreation)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avatarLabel = QtWidgets.QLabel(AICharacterCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatarLabel.sizePolicy().hasHeightForWidth())
        self.avatarLabel.setSizePolicy(sizePolicy)
        self.avatarLabel.setMinimumSize(QtCore.QSize(60, 60))
        self.avatarLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.avatarLabel.setSizeIncrement(QtCore.QSize(5, 5))
        self.avatarLabel.setStyleSheet("border: 1px solid black; padding: 10px;border-radius:5px;")
        self.avatarLabel.setScaledContents(True)
        self.avatarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avatarLabel.setObjectName("avatarLabel")
        self.horizontalLayout_2.addWidget(self.avatarLabel)
        self.avatarButton = QtWidgets.QPushButton(AICharacterCreation)
        self.avatarButton.setMinimumSize(QtCore.QSize(0, 0))
        self.avatarButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.avatarButton.setObjectName("avatarButton")
        self.horizontalLayout_2.addWidget(self.avatarButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(AICharacterCreation)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.nameLineEdit = QtWidgets.QLineEdit(AICharacterCreation)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_8 = QtWidgets.QLabel(AICharacterCreation)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.descLineEdit = QtWidgets.QLineEdit(AICharacterCreation)
        self.descLineEdit.setObjectName("descLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.descLineEdit)
        self.label_9 = QtWidgets.QLabel(AICharacterCreation)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.promptEdit = QtWidgets.QTextEdit(AICharacterCreation)
        self.promptEdit.setObjectName("promptEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.promptEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(AICharacterCreation)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.slider1 = QtWidgets.QSlider(AICharacterCreation)
        self.slider1.setMinimum(1)
        self.slider1.setMaximum(32768)
        self.slider1.setProperty("value", 512)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.slider1)
        self.label2 = QtWidgets.QLabel(AICharacterCreation)
        self.label2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2.setObjectName("label2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label2)
        self.label_4 = QtWidgets.QLabel(AICharacterCreation)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.slider2 = QtWidgets.QSlider(AICharacterCreation)
        self.slider2.setMaximum(20)
        self.slider2.setSingleStep(1)
        self.slider2.setPageStep(10)
        self.slider2.setProperty("value", 7)
        self.slider2.setSliderPosition(7)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.slider2)
        self.label_5 = QtWidgets.QLabel(AICharacterCreation)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.slider3 = QtWidgets.QSlider(AICharacterCreation)
        self.slider3.setMaximum(10)
        self.slider3.setProperty("value", 7)
        self.slider3.setOrientation(QtCore.Qt.Horizontal)
        self.slider3.setObjectName("slider3")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.slider3)
        self.label4 = QtWidgets.QLabel(AICharacterCreation)
        self.label4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName("label4")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label4)
        self.label_6 = QtWidgets.QLabel(AICharacterCreation)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.slider4 = QtWidgets.QSlider(AICharacterCreation)
        self.slider4.setMinimum(1)
        self.slider4.setMaximum(100)
        self.slider4.setProperty("value", 50)
        self.slider4.setOrientation(QtCore.Qt.Horizontal)
        self.slider4.setObjectName("slider4")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.slider4)
        self.label5 = QtWidgets.QLabel(AICharacterCreation)
        self.label5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label5.setObjectName("label5")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label5)
        self.label_7 = QtWidgets.QLabel(AICharacterCreation)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.slider5 = QtWidgets.QSlider(AICharacterCreation)
        self.slider5.setMinimum(100)
        self.slider5.setMaximum(200)
        self.slider5.setProperty("value", 101)
        self.slider5.setOrientation(QtCore.Qt.Horizontal)
        self.slider5.setObjectName("slider5")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.slider5)
        self.label1 = QtWidgets.QLabel(AICharacterCreation)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1.setObjectName("label1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label1)
        self.label3 = QtWidgets.QLabel(AICharacterCreation)
        self.label3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3.setObjectName("label3")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label3)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(AICharacterCreation)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.createButton = QtWidgets.QPushButton(AICharacterCreation)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout.addWidget(self.createButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AICharacterCreation)
        QtCore.QMetaObject.connectSlotsByName(AICharacterCreation)

    def retranslateUi(self, AICharacterCreation):
        _translate = QtCore.QCoreApplication.translate
        AICharacterCreation.setWindowTitle(_translate("AICharacterCreation", "AI角色创建"))
        self.label.setText(_translate("AICharacterCreation", "头像"))
        self.avatarLabel.setText(_translate("AICharacterCreation", "avatar"))
        self.avatarButton.setText(_translate("AICharacterCreation", "Upload Avatar"))
        self.label_2.setText(_translate("AICharacterCreation", "名称"))
        self.label_8.setText(_translate("AICharacterCreation", "描述"))
        self.label_9.setText(_translate("AICharacterCreation", "prompt"))
        self.label_3.setText(_translate("AICharacterCreation", "输出长度"))
        self.label2.setText(_translate("AICharacterCreation", "0.7"))
        self.label_4.setText(_translate("AICharacterCreation", "反应的创造性和随机性"))
        self.label_5.setText(_translate("AICharacterCreation", "Top-P"))
        self.label4.setText(_translate("AICharacterCreation", "50"))
        self.label_6.setText(_translate("AICharacterCreation", "Top-K"))
        self.label5.setText(_translate("AICharacterCreation", "1.01"))
        self.label_7.setText(_translate("AICharacterCreation", "重复惩罚"))
        self.label1.setText(_translate("AICharacterCreation", "512"))
        self.label3.setText(_translate("AICharacterCreation", "0.7"))
        self.cancelButton.setText(_translate("AICharacterCreation", "Cancel"))
        self.createButton.setText(_translate("AICharacterCreation", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AICharacterCreation = QtWidgets.QDialog()
    ui = Ui_AICharacterCreation()
    ui.setupUi(AICharacterCreation)
    AICharacterCreation.show()
    sys.exit(app.exec_())

